### ISSUE TITLE
Request - File Manager

### ISSUE THREAD

**Issue by lolicop123** [CTCaer/hekate#41] opened 2018-07-07 16:29 UTC
Although we have nx-shell, a File Manager built into Hekate would be cool.

**Comment by br4z0rf** [comment] 2018-07-09 13:50
Not OP but I figured it's related. I'd like something à la adb to pull and push files in the SD card so that we don't have to take it out every time.  
I could start working on a PR if you are interested.

**Comment by CTCaer** [comment] 2018-07-09 15:22
That's irrelevant with OP, yes, but an adb push/pull or even sideload would be very nice.

The problem is size constraints (~123KiB). So, I believe that payload launching would be the top priority.
If we can support that, then memloader is enough for all of these.

**Comment by mariogamer2** [comment] 2018-07-11 11:20
I think this is not worth it, even to select backup place, or something. (size...)

**Comment by CTCaer** [comment] 2018-07-11 14:15
A type of file browsing will be included for payload launching.
But a normal file manager? nope.

**Closed by CTCaer** 2018-07-11 14:15 UTC
Labels: wontfix
