### ISSUE TITLE
Automatically Lock Screen when is idle (like twrp swipe to unlock)

### ISSUE THREAD

**Issue by leonpano2006** [CTCaer/hekate#811] opened 2023-01-02 17:45 UTC
As title

**Comment by masagrator** [comment] 2023-01-02 17:49
You are writing this as issue, so you should inform somehow in title that this is in fact not an issue, but request

**Comment by CTCaer** [comment] 2023-01-02 20:52
Thanks for not wasting 10 seconds to glance over the short list of open issues.
Duplicate of https://github.com/CTCaer/hekate/issues/677

**Closed by CTCaer** 2023-01-02 20:52 UTC
