### ISSUE TITLE
hekate 5.2.0 fix archive bit issue

### ISSUE THREAD

**Issue by earandel** [CTCaer/hekate#420] opened 2020-05-05 17:45 UTC
I ran into a strange issue with the new archive bit fixing functionality in hekate 5.2.0.  I was trying to update the firmware.  The process that has always worked is to create a folder on computer, extract firmware files to the folder, delete file metadata using xattr (macOS oddity that ends up with ._* files on sd card if not done), move or copy the directory to the sd card, run hekate archive bit fix outside of Nintendo folder, and run choi to update the firmware.  When I tried fixing the archive bits using hekate 5.2.0, it said it completed successfully but when I booted into HOS, choi saw the folder with the firmware files as a file and wouldn't let me navigate to it.  The same was true for NX-Shell.  I tried renaming the folder and rebooted HOS a few times with no change.

I reverted back to hekate 5.1.4 (both payload and boatloader files on sd card) and ran the archive bit fix in both Nintendo and non-Nintendo folders since I was worried that hekate 5.2.0 may have messed something up now that it fixes archive bits across all files/folders on the sd card.  After doing this and rebooting into HOS, the choi update process worked as expected.

EDIT: SD card formatted as EXFAT if it makes any difference.

**Comment by CTCaer** [comment] 2020-05-05 18:03
What are the names of these folders?

(Also couldn't you report it a bit earlier? There's a new release now. ^^)

**Comment by earandel** [comment] 2020-05-05 18:06
The folder was called NX-10.0.2 when archive bit fixing was run.

I just saw that a new release went out after I posted this issue! :)  I should have jumped on this earlier.

**Comment by CTCaer** [comment] 2020-05-05 18:10
Yeah because it's easy to fix.

Issue is the the NX-10`.0.2`. This counts as an extension. Dot and 3 chars.

For now the way to fix that is to rename it to `NX-10_0_2`

**Comment by earandel** [comment] 2020-05-05 18:11
Makes sense.  Thanks for the quick response!

**Comment by CTCaer** [comment] 2020-05-05 18:13
Hmm. Release has low count of downloads for now. I may update the release.

**Comment by CTCaer** [comment] 2020-05-05 18:25
@earandel fixed with https://github.com/CTCaer/hekate/commit/9698cbc9d71b1f26e79bcb70edc6d136ea043aee

Release zip updated. Please test.

**Comment by CTCaer** [comment] 2020-05-05 19:02
Yep, confirmed fixed.

**Closed by CTCaer** 2020-05-05 19:02 UTC
Labels: Informative, bug, fixed

**Comment by earandel** [comment] 2020-05-05 20:59
Reproduced issue on 5.2.0 and tested latest 5.2.1 version to confirm fix worked successfully.  Thank you!

**Comment by CTCaer** [comment] 2020-05-05 21:15
Thanks for confirming.
