### ISSUE TITLE
v5.1.X freezes on eMMC SYS backup with existing backed up partitions

### ISSUE THREAD

**Issue by Ninoh-FOX** [CTCaer/hekate#355] opened 2020-03-02 09:24 UTC
when the console go to make a copy of the partition BCPKG2-4-SafeMode-sub this is freezes in overwriter mode (if you has a previeus backup)

**Comment by CTCaer** [comment] 2020-03-03 03:18
This is probably related to https://github.com/CTCaer/hekate/issues/338

Please try with the new release because I fixed some heap/list issues.

**Comment by CTCaer** [comment] 2020-03-07 07:57
Seems that this issue was resolved (#338). Try again with v5.1.2 / 0.8.5.

**Comment by Ninoh-FOX** [comment] 2020-03-07 10:51
same error, only work if you do a new backup, overwritter not work.

**Comment by CTCaer** [comment] 2020-03-07 11:24
Ah that's what you meant. You are supposed to press the POWER button. It says so.

**Comment by Ninoh-FOX** [comment] 2020-03-07 11:40
Yes, I press power, but when go to make the BCPKG2-4-SafeMode-sub  backup, the screen go to back and the console is freeze.

**Comment by CTCaer** [comment] 2020-03-07 12:00
Yeah just checked it. I can confirm.

**Comment by CTCaer** [comment] 2020-03-09 07:14
Fixed with https://github.com/CTCaer/hekate/commit/8d5c52f087584d8f0c43fca2375abc49ed2da420
Relevant issues: #355, #362 and #338.

Because this regression affects way more stuff than it seems, I will do a critical hotfix release in the next hours-days.

Issue will be closed only when the release is ready.

**Closed** 2020-03-21 21:02 UTC
Labels: bug, fixed
