### ISSUE TITLE
[Enhancement] - Battery cycles

### ISSUE THREAD

**Issue by Issue-maker-9000** [CTCaer/hekate#888] opened 2023-09-11 20:06 UTC
For all the useful battery info it gives, it doesn't display the battery cycles which I think can be quite useful.

**Comment by masagrator** [comment] 2023-09-12 11:54
I am quite curious because when last time I have tested this readings seemed unreliable.

Like first time when I was reading it, that was 250, after few hours of charging I got 251 and an hour later all of a sudden it's 257.

**Comment by CTCaer** [comment] 2023-09-12 12:43
@Issue-maker-9000 
That won't be implemented since HOS clears it when it exceeds more than 2 charge cycles and adds it to its own cycle counter.
So there's nothing to show if it will always be less than 3 cycles (300%).

@masagrator 
Did you read the description on how it works? It is the cycle register.
It saves cycle percentage not a pure number.
65535% means 655.35 cycles (251%: 2.51, 257%: 2.57).
But anyway, it's useless since hos clears it.

**Closed by CTCaer** 2023-09-12 12:43 UTC

**Comment by masagrator** [comment] 2023-09-12 13:28
> Did you read the description on how it works? It is the cycle register.

Yes, but since it max limitation is 655 cycles and it resets, it is not most people are searching for.

**Comment by CTCaer** [comment] 2023-09-12 14:51
Again, the issue is not the reg size limitation and it doesn't reset on its own.
I already said why it's useless and not what people are searching for.
HOS sets it to 0.96 when it exceeds 2.96 charge cycles.

**Comment by Issue-maker-9000** [comment] 2023-09-12 17:35
> @Issue-maker-9000 That won't be implemented since HOS clears it when it exceeds more than 2 charge cycles and adds it to its own cycle counter. So there's nothing to show if it will always be less than 3 cycles (300%).

Ah that really sucks. makes sense now why no homebrew shows cyclecount. Thanks for the answer and hekate ofcourse!

**Comment by CTCaer** [comment] 2023-09-12 18:11
There's a homebrew for that since 3-4 years ago ([BatteryInfo.nro](https://cdn.discordapp.com/attachments/458344156184707077/688849543097483414/BatteryInfo.nro)). And any homebrew can show it.
HOS saves it first before clearing the actual hw and that data is exposed.

**Comment by Issue-maker-9000** [comment] 2023-09-12 21:56
> There's a homebrew for that since 3-4 years ago ([BatteryInfo.nro](https://cdn.discordapp.com/attachments/458344156184707077/688849543097483414/BatteryInfo.nro)). And any homebrew can show it. HOS **saves** it first before clearing the actual hw and that data is exposed.

Ohh I misunderstood, makes sense now so hekate reads it out directly from the battery management chip or whatever it uses. While that hb application gets it from os itself. Correct?

I honestly missed that hb app, thanks for the link! Seem to have quite a bit of wear for the cycles it has gone through, 93% health on 235 cycles while ninty rates it for 80% health on 800 cycles. Assuming it is accurate of course

**Comment by masagrator** [comment] 2023-09-12 22:08
> Assuming it is accurate of course

This is saved to nand, so every backup restoration or switching between emummc and sysmmc regularly will cause this reading to being unreliable.

**Comment by CTCaer** [comment] 2023-09-13 09:35
Yeah the only 100% reliable way is to only use one mode and never restore.
On the other hand it can be manually increased/fixed, assuming someone notes them down.
Best way is to note down the counter when a copy is done. Each increment on both sys and emu counts.
