### ISSUE TITLE
Unable to boot into Hekate 6.0.1 with RCMLoader

### ISSUE THREAD

**Issue by Danfun64** [CTCaer/hekate#804] opened 2022-12-25 05:01 UTC
For whatever reason, Hekate refuses to boot into Hekate 6.0.1 directly from the firmware file through RCMLoader. When I try to do so, I get a black screen and have to hard reboot my Switch. However, I am able to load 6.0.1 from the bootloader directory in my SD card when I use the 6.0.0 firmware in RCMLoader.

**Comment by urherenow** [comment] 2022-12-25 05:49
This has already been posted and closed. Read the damn release notes before downloading and you’d know that you don’t need to update your RCMloader. Put 6.0 on it and leave it alone. You will always load the most recent from /bootloader/update.bin.

**Comment by impeeza** [comment] 2022-12-25 06:47
An old case of RTFM.  

This is duplicate of https://github.com/CTCaer/hekate/issues/802

Please if you need help or support go to the proper site. Discord and gbatemp are examples. This space is for hekate issues only


More info on the posts:
https://gbatemp.net/threads/fake-rcmloader-dongles-in-the-wild.620470/post-10024785


https://gbatemp.net/threads/fake-rcmloader-dongles-in-the-wild.620470/post-10031676

**Closed** 2022-12-25 18:11 UTC
