### ISSUE TITLE
Not working on latest system version

### ISSUE THREAD

**Issue by ThePsycrow** [CTCaer/hekate#228] opened 2019-06-28 21:46 UTC
When will we be able to use it as normal on 8.1.0?  Keeps having a problem with the pkg1 when trying to run the stuff I used to be able to run before 8.1.0.

**Comment by fennectech** [comment] 2019-06-28 21:54
Soon ™

**Comment by fennectech** [comment] 2019-06-29 02:01
The current way to use homebrew on 8.1.0 is by atmosphere’s fusee-primary until ctcaer finishes polishing hekate.

**Comment by nicoboss** [comment] 2019-06-29 15:23
They already have hekate working on 8.1.0 privately for 3 days - no idea why this changes still aren’t pushed yet. If the speculations are true and NYX is the successor of hekate then probably we get a working hekate like payload today: https://twitter.com/CTCaer/status/1144987055811944448
And if not CTCaer will probably have way more time in for hekate now that NYX seems to be done.
By the way this issue is a duplicate of https://github.com/CTCaer/hekate/issues/226 and so can be closed.

**Comment by CTCaer** [comment] 2019-06-30 03:49
https://github.com/CTCaer/hekate/commit/12f8f055eb94429ebd15395812d663b807fe2579

**Closed by CTCaer** 2019-06-30 03:49 UTC
