### ISSUE TITLE
Failure to backup BOOT0 during NAND backups/emuMMC creation with hekate/Nyx 0.8.0

### ISSUE THREAD

**Issue by suppai** [CTCaer/hekate#231] opened 2019-06-30 05:20 UTC
With the current Nyx release, every time I try to backup my NAND or create an emuMMC it fails to write to my SD card. For NAND backups/file-based emuMMC creation I get `fatal error when writing to the SD` when trying to backup BOOT0, and with partition-based emuMMC creation I get `Error writing 8192 blocks \@LBA` (it attempts to backup BOOT0 thrice and fails, then aborts). hekate 4.10.1 can create NAND backups without issue, and reading/writing works fine on PC, from fusee, in Horizon, etc. I tried multiple fresh formats of my SD with multiple different applications to make sure it wasn't at fault, and the issue persisted.

My SD card is a Samsung EVO+ 128GB microSDXC (MB-MC128D) formatted to FAT32, and my Switch is an unpatched console running firmware 1.0.0 (if that matters).

**Comment by suppai** [comment] 2019-06-30 09:31
Some additional info:

Perhaps this is due to SD card controller weirdness with certain cards *a la* the old Sandisk SD card issue, because the most recent iteration of this card, MB-MC128G *does* work, but MB-MC128D doesn't.

**Comment by suppai** [comment] 2019-06-30 09:54
Dumping fuses/bootrom/pk1/pk2/etc. works just fine-- just the NAND and emuMMC portions don't. Some screenshots: 

![download](https://user-images.githubusercontent.com/51038802/60395040-790ee980-9afb-11e9-8928-18eba30e1cdc.png)

**Comment by suppai** [comment] 2019-06-30 12:29
Per m4xw's recommendation on Discord I reformatted again and made sure the cluster size was set to 32k; this did not make a difference and I encountered the same errors.

**Comment by CTCaer** [comment] 2019-06-30 13:11
Samsung should not have that problem. There's should be sth with when you enter the backup screen.
I'll investigate

**Comment by suppai** [comment] 2019-06-30 13:18
Thank you. Let me know if there's anything I can do to help! Fwiw, I purchased this card from Best Buy and also ran h2testw on it, so I'm fairly certain it is a legitimate Samsung card.

**Comment by westonmyers** [comment] 2019-06-30 17:42
I'm just curious, could you pull the cards' info via Nyx for both?

`Console Info > Storage & Battery info > microSD`

**Comment by CTCaer** [comment] 2019-06-30 17:43
Btw this fails instantly. The moment it tries to write. That's because the 0% text is not even initialized on the first runs.

**Comment by suppai** [comment] 2019-06-30 22:26
@westonmyers 

![screen](https://user-images.githubusercontent.com/51038802/60402946-9c21b380-9b64-11e9-917a-ab854baf1854.png)

**Comment by CTCaer** [comment] 2019-07-01 08:29
So it's the older evo+ **U1**.
Haven't yet checked the whole code path to there, but I'll do it soon.

**Comment by Geranospiza** [comment] 2019-07-01 10:46
Same issue here. These are the sdcards I use. They both work in 4.10.1 and do their backups and stuff. Not working on 5.0.0 

![IMG_20190701_123556](https://user-images.githubusercontent.com/21951998/60430701-38e45f80-9bfe-11e9-8ce7-cb289531dfcb.jpg)

**Comment by CTCaer** [comment] 2019-07-01 11:28
I'll need some of you to test this in discord, hopefully today.

**Comment by ja3h** [comment] 2019-07-01 18:16
I'm unsure if it's exactly related so I'm unsure it it'll even be of help (if not then I'm sorry), but I am also having issues with creating eMMC backups on the newest Hekate with a definitely-legit SanDisk Ultra 256gb mSD, of the common/newest type you can readily buy on Amazon (tested via FakeFlashTest to be doubly-sure). 
No other software or even hardware has faced any issues with read/write to these cards - not even OFW - except Hekate and I have tried two different ones of the same types of cards (formatted in both exFAT and FAT32, in all variations of cluster size) and it's a no-go, with the same issues each time though for some extra info if it helps any, FAT32 does SOMETIMES create BOOT0 and BOOT1 and other times it won't. On times it won't, if I retry a few times it eventually does. The other backups fail at random times even with verification disabled. 
The card-specific data on my cards are the exact same as suppai's (except the capacity and mine is App perf class A1), however I get a different error code to suppai's and that is error code (2).

**Comment by suppai** [comment] 2019-07-02 11:13
@CTCaer I am tart#4321 on Discord, feel free to DM me! (I'm in ReSwitched and Nintendo Homebrew if you need a mutual server, or you can post an invite here to one you're already in, or wherever)

**Comment by CTCaer** [comment] 2019-07-02 20:41
Can you join retronx, there's a build attached there.

This was probably fixed

**Comment by suppai** [comment] 2019-07-02 23:55
@CTCaer Joined; if the build you mention is hekate 5.0.1r3, the issue remains, though the error message is slightly different: `Error writing 8192 blocks @LBA 00000000` and `Fatal error (1) when writing to SD card`.

**Comment by CTCaer** [comment] 2019-07-07 13:57
Seems that the issue stems from UHS mode. Aka low voltage 1.8V path.
Forcing 3.3V makes them work.

**Comment by CTCaer** [comment] 2019-12-08 17:53
Please try again with v5.1.0.

I added a function that makes sure that PMIC changed the voltage and also APB clock (used in many things) is not stressed as before.

**Comment by bellofiguoa** [comment] 2020-01-03 19:43
Hi i had the same problem with 5.1.1 and after retrying a couple of times it managed to both backup the NAND and create the emuMMC. I have the same sd as suppay

**Comment by CTCaer** [comment] 2020-01-05 12:43
I found the issue to that problem and it will be fixed.

Anyone that wants to test that fix, ping me at RetroNX discord.

**Comment by CTCaer** [comment] 2020-01-10 02:48
The fix is confirmed to be working. Next version will have it

**Comment by CTCaer** [comment] 2020-05-01 16:22
Fixed with the new SDMMC driver

**Closed by CTCaer** 2020-05-01 16:22 UTC
Labels: fixed internally

**Comment by migm16** [comment] 2020-09-23 20:22
i get error code (5) when i try to make a boot0/1 backup in hekate, i have the raw gpp from a year ago and forgot to get the boot0/1 files untill today, i have upgraded once.

**Comment by anroze00** [comment] 2022-11-22 19:51
> Fixed with the new SDMMC driver

I man i got the same issue may get some help?

**Comment by impeeza** [comment] 2022-11-22 21:04
This error was corrected two years ago, if you have the "same" problem, try to update Hekate, and if the problem continue, please go to an appropriate support site, discord or GBATemp are good start.
