### ISSUE TITLE
Nyx hangs on some SoC revs because of touch

### ISSUE THREAD

**Issue by N3MIS15** [CTCaer/hekate#247] opened 2019-07-01 07:40 UTC
Launching hekate stalls at the boot screen (Custom NX bootloader...) when i have sd card inserted. Launching without an sd card inserted launches the "old" style menu where i can then launch other payloads etc. Launching with autoboot enabled also works as intended.

I have tried cards formated with both fat32 and exfat, launching the payload from switchme chip, reboot to rcm and also launcing the payload again from within hekate itself. I also tried cards from different manufacturers.

 Please let me know if you require any other information as I am out of ideas of what to try to get this working.

FWIW It works just fine on my 4.1 ipatched switch via caffine.

**Comment by CTCaer** [comment] 2019-07-01 08:24
I wonder what your device doesn't like. I'll think of sth.

**Comment by chip1** [comment] 2019-07-01 10:07
I've the same problem. Tried to Update OFW from 6.2, to 7.01 and 8.1 without success

**Comment by Geranospiza** [comment] 2019-07-01 10:45
This happens to me as well. I mean, its not only the backup. Also fails to load CFW (Atmosphere). I've seen the github issue. Im on 8.1.0. I have 2 micro SD cards that have successfully backed up my system on hekate 4.10.1, no issues. None of them work in 5.0.0 One is a samsung U3, the other one SanDisc U1.

![IMG_20190701_123556](https://user-images.githubusercontent.com/21951998/60430659-1eaa8180-9bfe-11e9-8932-6b37f317b336.jpg)

**Comment by CTCaer** [comment] 2019-07-01 11:26
@chip1 @Geranospiza 
Please don't mix issues with booting with issues in loading nyx. They are completely separate things.
Problems with booting are probably a stack corruption thing, while loading Nyx, needs more solid investigation (although I have an idea).

And I hope I will see some of you in discord so you can try test builds

**Comment by N3MIS15** [comment] 2019-07-01 11:28
Which discord server?

**Comment by CTCaer** [comment] 2019-07-01 11:31
I'm only in one server, retronx

**Comment by chip1** [comment] 2019-07-01 13:38
@CTCaer: I mean the nyx boot issue, Stuck on bootscreen. Tried also different SD cards with a fresh and clean configuration. Older versions and with classic GUI everything is running well.

**Comment by CTCaer** [comment] 2019-07-01 20:33
I added some specific wait times that were missing. Please check in discord.

**Comment by CTCaer** [comment] 2019-07-01 21:48
The issue is newer models of touch panels

**Comment by Geranospiza** [comment] 2019-07-01 21:52
This is not true. I had my switch one day before oficial release and Nyx
hangs on me.

**Comment by CTCaer** [comment] 2019-07-01 21:55
hmm can you test a build then in retronx discord?

**Comment by Geranospiza** [comment] 2019-07-01 22:00
Of course. Will be home in 2 hours. DM me the build. Im Rogers, the dude
with the 512gb samsung evo plus U3 card.

**Comment by CTCaer** [comment] 2019-07-01 22:03
they are attached there. you just need to rename them to nyx.bin.

**Comment by chip1** [comment] 2019-07-02 06:40
@CTCaer: the new build gives a black screen after bootlogo.

**Comment by CTCaer** [comment] 2019-07-03 18:27
Turned out the problem was different POR values for different SoC revisions.

**Comment by N3MIS15** [comment] 2019-07-03 20:56
Confirmed fixed.

**Comment by CTCaer** [comment] 2019-07-03 21:05
This will be closed when the commit that has the fix gets commited.

**Comment by Webbeh** [comment] 2019-07-03 22:10
Hi.

I'm not sure whether the issue is the same or not, but I've got a XAJ1001**** Switch, with firmware 8.1.0.

Can send the payload just fine, works with both the GUI and the old style menus...

...until I create an emuMMC (RAW partition). After that, injecting hekate with SD card in freezes on the Nyx' boot screen (Custom NX bootloader). Injecting hekate without SD card displays the old style menu.

I tried both with and without this fix : https://github.com/CTCaer/hekate/issues/235#issuecomment-507036263 


Also, before creating emuMMC, the "Launch" menu displayed all the options (Atmosphere, ...), and after creating an emuMMC (without powering off or removing the SD card), it said that there is no config file available.
Going on the SD Card information screen showed the available space on the card, as expected.

Is this related to OP's issue ?

**Comment by CTCaer** [comment] 2019-07-06 21:25
This was fixed by various commits, but most cases were this: https://github.com/CTCaer/hekate/commit/5b919cb12e4bbd33c81790611277597939e3983f

**Closed by CTCaer** 2019-07-06 21:25 UTC
Labels: bug, fixed internally
