### ISSUE TITLE
Hekate unable to start when EmuMMC is disabled

### ISSUE THREAD

**Issue by vproper** [CTCaer/hekate#666] opened 2021-09-25 19:32 UTC
When I disable EmuMMC in Hekate EmuMMC settings, it corrupts the emummc.ini file, so Hekate is unable to start properly and it shows only black screen. Erista unpatched model

**Comment by BestPig** [comment] 2021-09-25 22:13
Oh, I got the same issue yesterday.
I didn't remember if I was in 5.6.1 or 5.6.2.
I used a File Based emummc on an Erista unpatched if it can helps.

![unknown](https://user-images.githubusercontent.com/363342/134787127-1ccc9bbd-cd95-4da6-988e-a7936b8b34e6.png)

**Comment by DavidBuchanan314** [comment] 2021-09-25 22:30
Anecdotally, two instances of this exact same emummc.ini corruption have cropped up recently in the reswitched user support channels. I don't have the specifics, but I thought I'd add this as evidence towards it *not* being random FS corruption unrelated to hekate.

**Comment by DavidBuchanan314** [comment] 2021-09-25 23:47
A total stab in the dark as to what the cause could be, but on this line `path` could be null, which might make strlen unhappy:

https://github.com/CTCaer/hekate/blob/af7bee2231560a708129e7f417c7f0fd036d7692/nyx/nyx_gui/frontend/fe_emummc_tools.c#L116

**Comment by vproper** [comment] 2021-09-26 06:52
> A total stab in the dark as to what the cause could be, but on this line `path` could be null, which might make strlen unhappy:
> 
> https://github.com/CTCaer/hekate/blob/af7bee2231560a708129e7f417c7f0fd036d7692/nyx/nyx_gui/frontend/fe_emummc_tools.c#L116

So, I think what we need is to check if the string is null before proceeding to strlen

**Comment by urherenow** [comment] 2021-09-26 08:00
0 is not null. It's already set to 0.

**Comment by CTCaer** [comment] 2021-09-26 09:12
Yes this should check if path is NULL.
The issue can only happen when disabling emuMMC. And it produces a garbage path, suffixed with "/Nintendo" string.
In the end, what happens from all that is a heap corruption because emummc path max size is 128 chars.

Thing is that I wonder why strlen finds data there.
Normally BPMP sees zeros for the first bytes in 0 address. (Yes, BPMP doesn't abort reading there.)

**Comment by DavidBuchanan314** [comment] 2021-09-26 17:11
is address 0 writable? Perhaps a bug elsewhere is causing data to be written to NULL.

**Comment by CTCaer** [comment] 2021-09-27 17:39
It's not writable. Reason why I wonder.
But anyway, I will push a release tomorrow.

**Comment by rashevskyv** [comment] 2021-09-30 06:27
Any progress?

**Comment by Viperbite** [comment] 2021-09-30 19:20
Where did id=0x8eaff come from?? Maybe it doesn't matter, but in my old emummc.ini it looks like this...
![1111](https://user-images.githubusercontent.com/47257874/135517266-736c690c-0d9c-4d00-858a-693e74c74b89.jpg)

**Comment by Masamune3210** [comment] 2021-10-01 00:51
If its what I think it is, going into nyx and updating your emummc settings will generate the id, its used to identify that specific emummc instance. If I'm not, ignore me

**Comment by CTCaer** [comment] 2021-10-01 10:39
@Viperbite it's normal in newer versions. Before, the id was always 0 because it was obsolete and not used. Now it gets autogenerated from path.

As for progress on path issue; the actual resulted issue on that is that compiler optimizes out later path checks because path was read once without checking. So I needed to find time to make sure that this doesn't happen elsewhere.
Maybe today, I'll do a release.

**Comment by CTCaer** [comment] 2021-10-01 15:52
Fixed in latest release (v5.6.3/1.0.8)

**Closed by CTCaer** 2021-10-01 15:52 UTC
Labels: bug, fixed
