### ISSUE TITLE
Blue when launching atmosphere from Hekate

### ISSUE THREAD

**Issue by AxelLaisney** [CTCaer/hekate#975] opened 2024-06-12 12:09 UTC
Hello! Despite installing everything updated (hekate and atmosphere) I can't launch atmosphere from hekate. But I can launch it directly using the new fusee.bin. I am using rekado to inject the payload and yes I updated the fusee.bin in bootloader/payload file by the one providing on atmosphere github page. I have a switch v1.

**Comment by CTCaer** [comment] 2024-06-12 20:35
use v3 and update all relevant payloads.
Duplicate of https://github.com/CTCaer/hekate/issues/969

**Closed by CTCaer** 2024-06-12 20:35 UTC
