### ISSUE TITLE
hekate v5.3.0 Crash to RCM after "Booting..." on 9.0.0-9.0.1 FW

### ISSUE THREAD

**Issue by SwiftMove** [CTCaer/hekate#461] opened 2020-06-21 03:06 UTC
hekate v5.3.0 is crashing to RCM mode with FW 9.0.0 or FW 9.0.1 installed. I didn't test any other FW's lower than those. Happens regardless of Atmosphere version. I've tested on both Atmosphere v0.9.4 and v0.13.0. I can boot to FW 9.0.0 or FW 9.0.1 using fusee-primary from Atmosphere v0.13.0 just fine. If I switch to any FW higher than 9.1.0, then hekate v5.3.0 boots just fine. But as soon as I downgrade to FW 9.0.0 or FW 9.0.1, it just crashes to RCM mode right after "Booting..." is shown on the display (see pic below).

![hekate v5 3 0 Crash on 9 0 0 FW](https://user-images.githubusercontent.com/51183018/85215701-432ccb80-b331-11ea-9717-f35c5e69bf66.jpg)

**Comment by Ultracoolguy** [comment] 2020-06-21 11:20
I can confirm this bug(I'm using 9.0.1). For me booting using fusee-primary worked, so if someone wants to boot into their CFW that can work in the mean time.

**Comment by CTCaer** [comment] 2020-06-21 13:17
This is a duplicate of the issue below it and also pinned.
It was fixed and a binary was supplied until the next official release. 
Check: https://github.com/CTCaer/hekate/issues/460#issuecomment-647019768

Blue screen means panic. It can react in 2 ways. Show the color or just reboot into rcm.

**Closed by CTCaer** 2020-06-21 13:17 UTC
Labels: duplicate
