### ISSUE TITLE
Part based emuMMC on OLED and resizing issues

### ISSUE THREAD

**Issue by Tecd0c** [CTCaer/hekate#675] opened 2021-10-26 22:21 UTC
The new OLED is having a 64GB NAND.
Creating file based emuNAND works fine with Hekate. 
Unfortunately Hekates Partition Manager fails to create the SD partition for Part1 partition.

After selecting to prepare the partitions, it finishes with done, but no partitions are created.
If you restart the Partition Manager, it asks you again if you want to create the partitions.

**Comment by Leerz** [comment] 2021-11-28 10:31
> The new OLED is having a 64GB NAND. Creating file based emuNAND works fine with Hekate. Unfortunately Hekates Partition Manager fails to create the SD partition for Part1 partition.
> 
> After selecting to prepare the partitions, it finishes with done, but no partitions are created. If you restart the Partition Manager, it asks you again if you want to create the partitions.

additional information

when you create a 29x2 , it makes 2 new partitions 32gb each
that's why  hekate doesn't see it.

i have tried several things, using an windows based formatter to make the 64gb partition, but it seems hekate  is looking for a switch partition and won't see unallocated space to make the new partition on. 

also tried making a nand dump, boot0/1, keys, 
and running it through nxnand manager, unfortunately, it seems hekate is looking for the first partition (since it always creates the partition at the end) , so it can't see (i'm probably wrong but that's what's currently happening)
i will try again with
making the 29x2 from hekate (so it's at the end) , merge the 2/ delete, the put in the 64gb via emutool (can't use nxnand since it will overwrite everything)

**Comment by Leerz** [comment] 2022-01-14 14:00
update - easiest i've realized is as follows

1. partition 29x2 with hekate
2. windows disk mgmt, delete both 29gb partitions
3. from the unallocated space, create 1 58.xGB exfat partition
4. open hekate again and create emummc, it should now detect the 64gb partition

**Comment by urherenow** [comment] 2022-01-14 14:10
Confused... why wouldn't that be 32x2?

**Comment by Leerz** [comment] 2022-01-14 14:20
> 
hekate doesn't support 64gb yet, (64gb is 58.xx something gb)

and 29gb is 32gb / 32,000,000,000 divided by 1024x1024x1024= 29.8023223877 Gb


see below
> Use resized. On the slider, choose 12GB or lower (16GB or lower if external partition tool).
> 
> Have in mind that I haven't decided yet if I will add support for FULL on OLED (because even if you can use that space by moving stuff there, I still consider it waste of space).

**Comment by chrisssj2** [comment] 2022-01-18 16:14
> 
@Leerz 
What exactly is the benefit of having a 58GB partition? 
I did 12 GB in partition manager hekate and then created file sized emunand and when in switch homescreen storage I see 54,9GB storage. 
Im also trying your way with 2x 29GB and deleting partitions in windows. Now I see 58.X GB 2nd partition in windows. 
Now creating emunand as we speak... but I don't see the advantage of it, esp since my first method already somehow says I have 54,9GB storage...

**Comment by Ninjistix** [comment] 2022-01-27 06:38
on 5.7.0 on the oled console the slider goes from 12, to full, creating full doesn't make the partition, anything lower than 12 works, but using 12 gives you around 5gb total size.

**Comment by CTCaer** [comment] 2022-01-27 07:19
It's supposed to work in Nyx 1.2.0 (and I just forgot this issue open).

Show me a screenshot of the pop up from Create emuMMC -> SD Partition
Also what number does FULL say in Partition SD screen after you move the slider there?

**Comment by Ninjistix** [comment] 2022-01-27 08:25
[slider at full]
![nyx20220127_031525](https://user-images.githubusercontent.com/12572974/151319966-f28f2332-822c-471e-82c4-5ec3f81f6524.jpeg)
![nyx20220127_031747](https://user-images.githubusercontent.com/12572974/151320042-78b28151-2fba-4904-a316-553184914868.jpeg)

Create emuMMC -> SD Partition [FUll]
![nyx20220127_031757](https://user-images.githubusercontent.com/12572974/151320084-3d850d4e-344e-4566-bce4-9b14607dcbcd.jpeg)



[slider at 12]
![nyx20220127_031819](https://user-images.githubusercontent.com/12572974/151320141-c662502f-e32d-4a5f-a18f-4236040ae86d.jpeg)
![nyx20220127_032006](https://user-images.githubusercontent.com/12572974/151320166-f61fe47c-b403-44cc-8bcc-445f7aa9f586.jpeg)

Create emuMMC -> SD Partition [12]
![nyx20220127_032017](https://user-images.githubusercontent.com/12572974/151320199-a37509ec-4cb6-4233-967a-e2f915514859.jpeg)

**Comment by Ninjistix** [comment] 2022-01-27 08:29
when using 12 as an option this is what you get when you boot into the console
![2022012703274500-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151320921-1370baff-5a85-41c9-b413-d161e16fa3aa.jpg)
.

**Comment by CTCaer** [comment] 2022-01-27 14:18
I don't have an available SD card right now.
Is it possible to test the following with the attached nyx from nyx.bin?
```
1. Set slider to 4GB
2. Create emuMMC
3. Repeat for sliders with GB of 5 to 12 and 58 (full). Aka 13 more times
4. Tap on screen with 3 fingers or the capture button on joycon to get a screenshot
5. Get me the _log.bmp from /bootloader/screenshots that has the user resized number prints.
```

I disabled actual eMMC reads and SD writes for the main partitions to speed up the process.
It will still right stuff but it should be ultra fast.

[nyx.zip](https://github.com/CTCaer/hekate/files/7951115/nyx.zip)

**Comment by Ninjistix** [comment] 2022-01-27 17:56
[screenshots.zip](https://github.com/CTCaer/hekate/files/7952762/screenshots.zip)
here's the whole screenshots folder, did everything from 4 to 2x full, for the 2x I tried to create emuMMC on both raw1 and 2

**Comment by CTCaer** [comment] 2022-01-27 18:45
Thanks. This will pin point the exact resizing issue, although I bet it's fatfs.

As for FULL for OLED, that's my mistake. I forgot I cut 1MB from the final size. And OLED eMMC's GPP partition aligns perfectly to 16MB and so the check was finding 1MB less and didn't allow it.

**Comment by chrisssj2** [comment] 2022-01-27 18:48
> when using 12 as an option this is what you get when you boot into the console ![2022012703274500-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151320921-1370baff-5a85-41c9-b413-d161e16fa3aa.jpg) .
I can confirm had this same thing when using 12. half your space seems to be used somehow.... I did the partition trick in windows and now have 58 GB in switch OS shown.! :)

**Comment by CTCaer** [comment] 2022-01-27 20:23
@Ninjistix Yep FatFS issue. 
I give 9615MB (user_sectors) to fatfs to format
![image](https://user-images.githubusercontent.com/3665130/151437416-a5e80b35-01f0-4f9f-833b-d81f22bac9fe.png)

I wonder if the other values (< 12GB) also have the issue.
You can check that if you mount emummc with UMS to PC and run hacdisktool or whatever on it.
Then mount USER with bis keys.

Also don't do the double ones. They are not useful because they are exactly like the single one, only to an upper offset.

**Comment by Ninjistix** [comment] 2022-01-27 22:04
should I try using exfat micro sd card to create the emuMMC?

**Comment by CTCaer** [comment] 2022-01-27 22:40
> should I try using exfat micro sd card to create the emuMMC?

it doesn't matter. hekate will always format it to fat32. Also that has nothing to do with what happens in that partition.
I use FatFS to format USER. But that doesn't touch the rest of the card. So if you start with MBR or GPT or SFD with FAT32 or FAT or FAT16 or exFAT, it doesn't matter basically

Can you try this one?
Create 12GB and boot it and see what space it has.
[nyx.zip](https://github.com/CTCaer/hekate/files/7954258/nyx.zip)

**Comment by Ninjistix** [comment] 2022-01-27 23:28
recreated the 12gb partition and emuMMC

![nyx20220127_181616](https://user-images.githubusercontent.com/12572974/151460236-1c55ab0e-4f05-410a-83f6-b48add207948.jpeg)
![nyx20220127_181616_log](https://user-images.githubusercontent.com/12572974/151460238-f42e01d7-b296-4498-a80a-dcd8816ca5e3.jpeg)
![2022012718230700-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151460327-4ddcde68-c709-48ca-8efd-bb70ec0d6c60.jpg)

**Comment by CTCaer** [comment] 2022-01-27 23:37
Well thing is that I should be more careful next time.
That's free space, not total.

So the total is correct but free is wrong?
I also checked FatFS driver exported FSI info and it has the correct free space.

So here's the deal. You will need to mount it on PC and use hacdiskmount (run it as admin and choose the hekate eMMC GPP then use the BIS keys to mount USER).
Then I will need the first 2 sectors of USER. You can use any hex editor that supports physical disks. Choose the hacdiskmount drive and copy paste the 2 sectors (total of 0x400 bytes).

They will look something like 
![image](https://user-images.githubusercontent.com/3665130/151461161-eb32093a-9e97-430f-849a-2f8dee4fef33.png)

**Comment by Ninjistix** [comment] 2022-01-27 23:42
ill do that now, but nothing is installed on the sysnand tho, so what's using up the space? why only 4.8gb of 12 free? shouldn't it be like 9.? and change?

**Comment by Ninjistix** [comment] 2022-01-27 23:54
![image](https://user-images.githubusercontent.com/12572974/151462553-2e517e6b-3e63-402f-973b-919f2c758e9d.png)
![image](https://user-images.githubusercontent.com/12572974/151462586-cf37f465-4c88-4026-98eb-e168505c236d.png)

**Comment by Ninjistix** [comment] 2022-01-27 23:58
[Untitled (X) - Selection.txt](https://github.com/CTCaer/hekate/files/7954637/Untitled.X.-.Selection.txt)

**Comment by CTCaer** [comment] 2022-01-28 00:24
So it's exactly the same with my test.
Its total size is 9615 MiB and free space is **9599 MiB**.
So HOS' PrFILE2 (FAT32/exFAT driver) is doing its mumbo jumbo as always.

OK. Phase 2 in case OLED has different PRF2SAFE record.
So, unlike any other emummc managers that resize, I actually restore that record, in order for HOS to have its custom proprietary FAT32 journaling that helps against corruption.

What I need is similar with what you've done.
Only that this time you will mount **eMMC** GPP and not emuMMC.
Mount USER, and extract the first 32 sectors, in the same raw format as you did in that file that you renamed to .txt.
(Btw can you make one dump as normal and one with zeros passthrough option in hacdisk enabled?)

These sectors in a factory formatted eMMC, have the special records. I can compare them these with the ones in a 32GB eMMC and see if they were changed.

**Comment by Ninjistix** [comment] 2022-01-28 00:54
apologies, I mounted the eMMC GPP first, this is the file for the emu RAW
[Untitled (X) - Selection emu raw.txt](https://github.com/CTCaer/hekate/files/7954829/Untitled.X.-.Selection.emu.raw.txt)
![image](https://user-images.githubusercontent.com/12572974/151468078-bf7c87e3-8083-40ca-8d9b-4a7cd6d18348.png)
![image](https://user-images.githubusercontent.com/12572974/151468094-b5cb19ab-22f3-4d29-9ee7-1b64e065a0c4.png)

**Comment by Ninjistix** [comment] 2022-01-28 00:58
user is 9.39GB
[Untitled (X) - Selection emu raw 32.txt](https://github.com/CTCaer/hekate/files/7954838/Untitled.X.-.Selection.emu.raw.32.txt)
user is 55GB
[Untitled (X) - Selection nand 32.txt](https://github.com/CTCaer/hekate/files/7954849/Untitled.X.-.Selection.nand.32.txt)

**Comment by CTCaer** [comment] 2022-01-28 14:33
Try 4GB and 12GB and boot them to see free space:
[nyx.zip](https://github.com/CTCaer/hekate/files/7959394/nyx.zip)

**Comment by Ninjistix** [comment] 2022-01-28 14:49
4GB
![2022012809415300-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151567687-702669ed-3ba6-45d9-9f23-edabc19d2c70.jpg)

12GB
![2022012809481100-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151567734-801986d4-9787-4d19-8a8a-d55acea006bb.jpg)

**Comment by impeeza** [comment] 2022-01-28 15:55
Wuaw guys, thanks a lot for all your efforts on this great product,  regards from Colombia.

**Comment by CTCaer** [comment] 2022-01-28 17:13
@impeeza don't spam.

@Ninjistix hmm so it's not the invalidated FSInfo.
What free space does that show on a pc when you mount USER?

**Comment by impeeza** [comment] 2022-01-28 17:17
> @impeeza don't spam.
> 
> @Ninjistix hmm so it's not the invalidated FSInfo. What free space does that show on a pc when you mount USER?

Sorry.

**Comment by Ninjistix** [comment] 2022-01-28 17:35
![image](https://user-images.githubusercontent.com/12572974/151594381-97ed8212-651d-40b3-8149-12c1d973920c.png)
![image](https://user-images.githubusercontent.com/12572974/151594447-8ce946e3-b9fd-4f3c-a6f3-ea2a9383d4db.png)

**Comment by Ninjistix** [comment] 2022-01-28 17:49
do you want me to dump the raw nand and resize it to see the difference in the sector's using nxnandmanager to resize it?

**Comment by Ninjistix** [comment] 2022-01-28 18:19
resized nand partition to 12gb
![2022012813124400-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151600273-457e6fe4-fd0c-42c6-8d65-70b3a6b4179a.jpg)

![image](https://user-images.githubusercontent.com/12572974/151600241-86cdb3e3-fc66-4992-93c6-4f4cfdef0b20.png)
[Removeable disk 1 - Selection resized 12gb nand.txt](https://github.com/CTCaer/hekate/files/7960918/Removeable.disk.1.-.Selection.resized.12gb.nand.txt)

**Comment by CTCaer** [comment] 2022-01-28 21:03
I think I found the the issue. try 12GB again:
[nyx.zip](https://github.com/CTCaer/hekate/files/7961817/nyx.zip)

**Comment by Ninjistix** [comment] 2022-01-28 21:18
cannot create emuMMC with current settings

Freezes at this point
![IMG_3122](https://user-images.githubusercontent.com/12572974/151622827-a398bccb-9851-45f3-8f33-b5f49c726493.jpg)

then the screen turns like this, (am I able to power off the system and boot back into hekate)
![IMG_3121](https://user-images.githubusercontent.com/12572974/151622605-0ed8cde4-4ad4-471d-a1a3-3ae518ec292f.jpg)


tried twice, same thing happens when trying to create the emuMMC

**Comment by CTCaer** [comment] 2022-01-28 22:04
Yeah sorry about that. Here's a new one that doesn't get out of bounds.
[nyx.zip](https://github.com/CTCaer/hekate/files/7962058/nyx.zip)

**Comment by CTCaer** [comment] 2022-01-28 22:17
Yep
[nyx.zip](https://github.com/CTCaer/hekate/files/7962120/nyx.zip)

**Comment by Ninjistix** [comment] 2022-01-28 22:25
> Yep [nyx.zip](https://github.com/CTCaer/hekate/files/7962120/nyx.zip)

success, this one works
![nyx20220128_172244](https://user-images.githubusercontent.com/12572974/151629762-957d6f35-d566-487c-8fbc-11dc9c4cd15d.jpg)
![2022012817223500-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/12572974/151629675-18fd2f84-1947-436f-887d-130da9ad52d4.jpg)

should I try the other partition sizes, 4/5/6/7/8 etc? or will this fix all of them?

**Comment by Ninjistix** [comment] 2022-01-28 22:36
side question, if I redo my partition on my main sd with this fix would I have to re-create my emuMMC also?

**Comment by CTCaer** [comment] 2022-01-28 22:41
No need. All of them had the same problem and it's fixed by that.

The issue was the bis driver. It was doing out of cluster bounds read/writes which was breaking the encryption/decryption.
And thus the filesystem was becoming corrupt.

The funny thing was that it was working but it was always eating half of the available clusters. Mounting it on pc and doing a repair would fix it.

That's how I found it. And then compared broken with repaired. And checked FatFS where it initializes that.
Then created a virtual drive because I knew fatfs was doing it right (works on fat formatting of sd) and checked the actual data that should be there. That pointed to bis driver doing stuff because I saw the cache indexes.


>side question, if I redo my partition on my main sd with this fix would I have to re-create my emuMMC also?

The fix is in the creation. Repartition will do nothing.
If you don't want to lose your emuMMC, just mount it in PC and do a `chkdsk {drive_letter}: /F`.
If asked to restore orphaned stuff to files, choose no. And then enable system files in explorer and delete FOUND.XXX folders.

**Comment by Ninjistix** [comment] 2022-01-28 22:51
so would that last nyx.bin be the complete fix? should be solved right? or do we need to test it on the older v1 consoles?

**Comment by CTCaer** [comment] 2022-01-28 22:55
Yeah https://github.com/CTCaer/hekate/files/7962120/nyx.zip is the full fix and can be used for now until I do a release.
(it also has the 58GB FULL fix).

**Comment by Ninjistix** [comment] 2022-01-28 22:57
sidenote tried to create a 58GB full took 16mins with the previous attachment. https://github.com/CTCaer/hekate/files/7962120/nyx.zip

**Comment by CTCaer** [comment] 2022-03-23 22:07
Please get the final and full fix in latest release.

**Closed by CTCaer** 2022-03-23 22:07 UTC
Labels: bug

**Comment by ProteinPig** [comment] 2022-03-28 13:20
HI, sorry to commit here after you guys closed it. 
I have the bug on my Switch Lite also, and I did the fix step. 
 - mount it in PC and do a chkdsk E: /F.
 - when asked to restore orphaned stuff to files, I choose no. 
 - but, when enable system files in explorer there is FOUND.XXX folders.

It is 6GB partition, I suppose it should 3.x GB free space. 
In windows, it shows 3.xGB, but in switch it shows there is 1.5GB.

So, anything else I should do?

**Comment by Masamune3210** [comment] 2022-03-28 14:40
Dont worry about using chkdsk, just reformat the filesystem. Likely things are still damaged somehow, especially since you told it to ignore orphaned files
