### ISSUE TITLE
Charging and power Information only update on user action (VOL/PWR)

### ISSUE THREAD

**Issue by GGLinnk** [CTCaer/hekate#22] opened 2018-07-01 22:22 UTC
When hekate is launched, at the bottom of the interface there is power infos,
thoses information never update exept when user do something like pressing Vol.+, Vol.- or Pwr.

Maybe make a auto update all 2 secs ?

**Comment by CTCaer** [comment] 2018-07-02 06:40
That's true and by design.

hekate is not threaded and that means that if there's a delay it will hinder with the user input.
It's possible to do it though, but it would add extra fat on the already limited payload space we have, for a feature that is not important.

So, just play with volume buttons if you want a live image.

I'll leave this PR open, until I decide if a possible implementation does not hinder with UX.

**Comment by CTCaer** [comment] 2018-07-06 16:35
I'll keep it that way for now, because this suggestion needs a new button check function to work like this.

It'll start being important when I implement a status bar.

**Comment by fennectech** [comment] 2018-07-06 21:40
What if we just update the screen by triggering a screen update even when user doesnt do input?              Is there a way to do a timer that we can periodically check without delaying UX?

**Comment by fennectech** [comment] 2018-07-06 21:41
Or.   We can just watch the number that changes most often and comparing it to its value when we last checked and update the screen if its changed.

**Comment by CTCaer** [comment] 2018-07-07 12:30
Closing in favor of https://github.com/CTCaer/hekate/issues/36

**Closed by CTCaer** 2018-07-07 12:30 UTC

**Comment by fennectech** [comment] 2018-07-07 17:39
So your going to make a status bar that updates seperately from the rest of the UI?
